name: Generated Rule Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install semgrep pyyaml

      - name: Generate Semgrep rules YAML
        run: python generate_semgrep_yaml.py owasp_rules.json semgrep_rules.yml

      - name: Run Semgrep scan
        run: semgrep --config=semgrep_rules.yml --json --output=semgrep_output.json || true

      - name: Summarize Semgrep results
        run: |
          python - <<'EOF'
          import json, os
          try:
              with open("semgrep_output.json") as f:
                  data = json.load(f)
              count = len(data.get("results", []))
              summary = f"## 🧠 Semgrep Security Summary\n\n✅ **{count} potential vulnerabilities found.**\n"
              print(summary)
              with open(os.environ["GITHUB_STEP_SUMMARY"], "a") as s:
                  s.write(summary)
          except Exception as e:
              print("Error reading Semgrep output:", e)
          EOF

      - name: Upload Semgrep output
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-artifacts
          path: |
            semgrep_rules.yml
            semgrep_output.json
