name: Semgrep Security Scan

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  semgrep:
    name: Run Semgrep Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (for Semgrep CLI)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep with custom security rules
        run: |
          semgrep --config=.semgrep/security-rules.yml --error
