name: Semgrep Security Scan

on:
  push:

jobs:
  semgrep:
    name: Run Semgrep Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Create custom JavaScript security rules
        shell: bash
        run: |
          mkdir -p .semgrep
          cat > .semgrep/security-rules.yml <<'EOF'
rules:
  - id: detect-hardcoded-aws-secret-js
    pattern: const aws_secret_access_key = "$SECRET"
    message: "Hardcoded AWS secret detected."
    severity: ERROR
    languages: [javascript]

  - id: detect-console-log-debug
    pattern: console.log($X)
    message: "Debug console.log statement found; remove before production."
    severity: WARNING
    languages: [javascript]

  - id: detect-eval-usage-js
    pattern: eval($EXPR)
    message: "Use of eval() can lead to code injection vulnerabilities."
    severity: ERROR
    languages: [javascript]

  - id: detect-function-constructor
    pattern: new Function($ARGS)
    message: "Use of Function constructor can lead to security issues."
    severity: ERROR
    languages: [javascript]

  - id: detect-settimeout-string
    pattern-either:
      - pattern: setTimeout("$CODE", ...)
      - pattern: setInterval("$CODE", ...)
    message: "Avoid using string arguments in setTimeout/setInterval; potential code injection."
    severity: ERROR
    languages: [javascript]

  - id: detect-document-write-js
    pattern: document.write($X)
    message: "document.write() can lead to XSS vulnerabilities."
    severity: ERROR
    languages: [javascript]

  - id: detect-innerhtml-assignment
    pattern: $OBJ.innerHTML = $VAL
    message: "Assignment to innerHTML can lead to XSS vulnerabilities."
    severity: ERROR
    languages: [javascript]

  - id: detect-localstorage-usage
    pattern: localStorage.setItem($KEY, $VAL)
    message: "Avoid storing sensitive data in localStorage."
    severity: WARNING
    languages: [javascript]

  - id: detect-unsafe-regex
    pattern: new RegExp($PATTERN)
    message: "Potentially unsafe regular expression. Validate input or use static patterns."
    severity: WARNING
    languages: [javascript]

  - id: detect-insecure-http
    pattern: fetch("http://$URL", ...)
    message: "Use HTTPS instead of HTTP for secure data transmission."
    severity: ERROR
    languages: [javascript]
EOF

      - name: Run Semgrep with custom rules and generate SARIF report
        run: semgrep --config=.semgrep/security-rules.yml --sarif --output=semgrep-results.sarif
        continue-on-error: true

      - name: Upload SARIF results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif
